language: c
 
install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console mono-xsp
  - mozroots --import --sync
 
script:
  - xbuild ./TestSharp.sln /p:"Configuration=OSX;Platform=Any CPU" /p:"DefineConstants=TRAVIS_CI"
  - nunit-console ./TestSharp.Tests/bin/MacOSX/TestSharp.Tests.dll
